language: node_js
node_js:
- 10.16.0
services:
- docker
cache:
  npm: true
  directories:
  - "~/.cache"
install:
- npm ci
before_script:
- npm i -g vue-cli
script:
- npm run lint
- npm run test:unit
before_deploy:
- BASE_PATH=/pdes-tp-buggysoft/ npm run build
- BASE_PATH=/ npm run builds3
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: "$GITHUB_TOKEN"
    keep_history: true
    local_dir: dist
    on:
      branch: master
  - provider: script
    script: bash docker_push.sh
    on:
      branch: master
  - provider: s3
    bucket: "buggysoft"
    skip_cleanup: true
    local_dir: buildS3
    secret_access_key:
      secure: JS1SeTklrljg6gil3GDNn7yKMf9X8i7GeDm4Z1BUE9NKjT2J8arekCoqGlN/xOhhadWH2otpeowTdQpil5dMLRb4zfQRYU+GVA7yzeDpPEP1FXzMmHuKsqSR2IXwCn/2oHfOq04nzBGh2EjKByx1Dp7rcNfiU0QYXRDvVRCOhaRteTyBwknoelXtF6iK744PULH/VL1vaD5IlFy3N2YUyCoMXixOIE10cRboaNHw6ZwJU9zSVcI0fDj5OwaVHIhphLWz6otsSbk3evglJsm19qJQEUpVjDQHnCGTY0GePCgSivM9sXvdh4PqP4FJxbQXn5ztb/RqyEmci+BuCZIIf79bGSPL+ydn6o1DFlm2YeqoWW/95PPoa5JFKoBdQBuymet7ui9c+88XF+n5Uj+1oz3ukvDyDbFWwvnfJWt9OKDx0Y4KvdWlU42LCImQG5+Zeg7TMIZwAoWOtEw2T31yLJxfkPzTAc+cSmJJjMqbBUba5UF26WNUPI3ZiqqbQAu4TZb20XPlcSjCg8jeTZT4vEsTvM/Hj1UwpDwrQpSugGr9neZayccCHTuEbgL8RcrgTIJQx0DyDZSOfTxJC2bMcqkHydyxOWTY+jaslTscgQUN4uDKmLz3EHzE3oe0HNgC5eRGJeyASRJLPU/Qx7sPK3/3sTIW5ze8GM07SV14x5o=
    access_key_id:
      secure: k9BiUaaldNhS4CCApXb8VqO/xLxnMBXciSUqSkTpcZr+TQOpyCIAa1XIWL7w0srnS+AYsQ2Y0o6z669qOaiwwVhpcjLKBILNUfzHGDJhpSy3czmA2X0yxAVqICBM9DHrzAEAhzOa+KqeSKu/qakgYrQyaLwT3oc7EtuXgjhnqQrEm96Xd4aE/6EHYJ5/HoMgzaJjyeYhQFVGAV4MJgsFghCtmfw4QCN34UgzcGFWdNPUKudslwlAgcFY8rl0XPNbQDRm6ADf6Fo7CPqDFxY9lxDqaJhims2jLwsMCwfbUgkmiPTsOcNvp++mr3vVyhsK0QQYpHU47AESHvmdPO/hWYApoSbIkj9QUJlKdi+uowUaR+R3S+mtCvo6JrYbEBbF5RbbZOQ0i/Hpro0iWMusOh8UtHnC664hBQ26tpWY53UQ7PmpYQJ+7sYjdUBR9yJYSEqT8dMZeA1bOV3zL0QiyzUfRyV3xvuDazup6K0ksssvBpMZN+gpkVk5CrgLKfwAahPWTZYjZ9SeiKhdZQNJlJwqBrkESnOI8gzzOg8U2utckuGbkJJOwO1xjcvYkLtTbykMlK6wLTIxLm7Pd5lst+CIc5SfIfQi09rLP1Uql1BWzvnXqAyPQsItwgp73FWO1lg6FKwxHrI1p2nFztLRZRcJQujQAVhg2SI8B7cZqE8=
    on:
      branch: master
env:
  global:
  - secure: cynPH0cfRr2uXMlZXFTexBRAX1pCfss6aDJKN7l6cEg4VRWsj0yCzRCOTuW0g8rM8ShNxeE3l55bNT7JghcQXrMG4IKWl5bk7qvrsr+I51cvG6liQNpd4u7/r8NH6SlDCvtZHB6/eKaaG0AQzuY0fEP0AJ9uxMC23KfCxs2aqXcRpcLQ0gvegFSdBG6LLag9sBncdhgZI8YtV1G/rgwBKuD1niPuAaCHMefUuO3MyhOTghj4meVZClnYX0VOc5UPM240AsZSnLMbOcON7LbusVujWkqthGdXjXHQsuGzHqjrPKz57XjzuAC8JbUpvj2GtFoNKTmfrqG1gLc0mNcUvycS33c0OLVM2eiuEvGfACSrKcmGXNT61C0s3ReOr6zUtdjlUmS1equxEDAeSRx7HagDdEiYM9DhTfblG0bPOpexvEJcRTQkFHsTWREQtLAZiqqw5/KN9bUuCE9R6I1Obwt7kP9+Yi4FSHLHlrqcN9djRBrRDFm0aaeMEEz15E38GVepARCzViZlDtsNAKl7jIsf/fFuCAqCowuwEWlP0gSxpvb3boqiEFcB5wTFDs+t+MsrJaiKF5DSxqWSi+xrSoLSsIDSe/7x1PqW6ZWasgdVCMcnXL4i+hAqvwg0XIXXJydjRxfRk3FMASgVkN0iZNYSd+bWwTXYcPTPn+l6Gv4=
  - secure: jo47W1GOJlq2mNtkhd3gfvw2QPBn4/VHS0REbfPkjarmiw4he3+LP8fCUDSoKAoZsbm1cbFohRkglDopedukGT409cQ062eBUV9eF6Kb9lZyaTn2ZcZNjYnijXCZr1NUMrum3Z3DT74EifeU+LptFRY+3NF+NgfW/QZHKaenPYYonbpHPcJXiLlev5g+LgCPrujQGV1w0nJpan6Hxtw+AtTIAQi17Ky/50gpN/s43gTqN5XUciqo0jNrwt3rQl0hD6nw8H9rmRRKqHfa98vtFpyDVz/s82H6oRvcHDIIOlbG/2MQVS9T6R3rJ6U5OjpWKMevdjSVQnZheaYlnG1wxQWRJY244la8Uw9+Gugqi6jmBNWZbiF2FlO010A/5MlLzpHBGTmbzNlVzUME9SAxg+2heC9dG2wiT9N7WPYH9c/+5dwWplYaDF6BaSAfa9+CZfCi/Yz2R2kaAC/WWduooNK0oT5dnwyBB7PwQIwBrcAHowFGq8T830bihOOUf6syCO1H/VyjsB4+jobLOSD7FvZQ0vGiVP9YW8MAiEzQqROxbM3yo1ePbu6z+CkAy7bFnwVjGZYdDAKfcPPEqK2zZ4rawrc8tAyQHRZw9E+0aRNlci/C4PmbbkMcADUydUMbfmgoPGrHpjv3/mhNgcH8CwxoXLHRp2ifvFORltdgsdI=
