export default {
  gold: 'gold',
  copper: 'copper',
  aluminum: 'aluminum',
  carbon: 'carbon',
  iron: 'iron',
  copperWire: 'copper_wire',
  gear: 'gear',
  circuit: 'circuit',
  processed_iron: 'processed_iron',
  processed_gold: 'processed_gold',
  processed_carbon: 'processed_carbon',
  processed_copper: 'processed_copper',
  processed_aluminum: 'processed_aluminum',
  processingUnit: 'processing_unit',
  robot: 'robot',
};
