export default {
  gold: 'gold',
  copper: 'copper',
  aluminum: 'aluminum',
  carbon: 'carbon',
  iron: 'iron',
  copperWire: 'Copper Wire',
  gear: 'Gear',
  circuit: 'Circuit',
  processed_iron: 'processed_iron',
  processed_gold: 'processed_gold',
  processed_carbon: 'processed_carbon',
  processed_copper: 'processed_copper',
  processed_aluminum: 'processed_aluminum',
};
